### ISSUE TITLE
k8s node group (minimum) disk size default variable is too low

### ISSUE THREAD

**Issue by ilfarpro** [terraform-yc-modules/terraform-yc-kubernetes#39]
When creating node group from YC Web UI you're forced to minimum disk size of 64 GB, however this not applies when working from terraform, where it says minimum disk size should be greater than 16 GB. 

I think it is necessary to edit variables.tf variable "node_groups". Right now disk_size set to 32, where it should be 64 as I guess.

**Comment by simple-elf** [comment]
But it works!! From terraform you CAN make disk 32GB and that's great!

**Comment by SultankaReal** [comment]
Merged here - https://github.com/terraform-yc-modules/terraform-yc-kubernetes/pull/45
Thanks for contributing!
