### ISSUE TITLE
Same security group for master and all node groups

### ISSUE THREAD

**Issue by dglushenok** [terraform-yc-modules/terraform-yc-kubernetes#7]
In case you don't want excessive access rules for master and node groups, in current version of module (1.0.0) it is impossible to assign different security groups for them.

**Comment by romati88** [comment]
Hello, your suggestion looks useful. We hope for PR with your solution or you can wait for updates from our specialists

**Comment by zhenyatsk** [comment]
https://github.com/terraform-yc-modules/terraform-yc-kubernetes/pull/27
